apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    kubebuilder.k8s.io: 0.1.12
  name: pipeline-controller-system
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    kubebuilder.k8s.io: 0.1.12
  name: pipeline-controller-role
rules:
- apiGroups:
  - concourse
  resources:
  - pipelines
  verbs:
  - get
  - watch
  - list
  - create
  - update
- apiGroups:
  - concourse.concourse-ci.org
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    kubebuilder.k8s.io: 0.1.12
  name: pipeline-controller-rolebinding
  namespace: pipeline-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-controller-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: pipeline-controller-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    kubebuilder.k8s.io: 0.1.12
  name: pipelines.concourse.concourse-ci.org
spec:
  group: concourse.concourse-ci.org
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
  version: v5alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    control-plane: controller-manager
    kubebuilder.k8s.io: 0.1.12
  name: pipeline-controller-controller-manager-service
  namespace: pipeline-controller-system
spec:
  clusterIP: None
  selector:
    api: pipeline-controller
    control-plane: controller-manager
    kubebuilder.k8s.io: 0.1.12
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    api: pipeline-controller
    control-plane: controller-manager
    kubebuilder.k8s.io: 0.1.12
  name: pipeline-controller-controller-manager
  namespace: pipeline-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      api: pipeline-controller
      control-plane: controller-manager
      kubebuilder.k8s.io: 0.1.12
  serviceName: pipeline-controller-controller-manager-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        api: pipeline-controller
        control-plane: controller-manager
        kubebuilder.k8s.io: 0.1.12
    spec:
      containers:
      - args:
        - --install-crds=false
        image: github.com/jchesterpivotal/knative-build-pipeline-poc/cmd/controller-manager
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
