---
apiVersion: concourse.concourse-ci.org/v5alpha1
kind: Pipeline
metadata:
  name: pipeline.example.com
spec:
  resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/concourse-courses/002-basics-of-reading-a-concourse-pipeline.git
  jobs:
  - name: successful-job
    public: true
    plan:
    - get: git-repo
    - task: job-task
      file: git-repo/tasks/successful/task.yml

  - name: failed-job
    public: true
    plan:
    - get: git-repo
    - task: job-task
      file: git-repo/tasks/failed/task.yml

  - name: flaky-job
    public: true
    plan:
    - get: git-repo
    - task: job-task
      file: git-repo/tasks/flaky/task.yml
