apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.concourse-ci.org
spec:
  scope: Namespaced
  group: concourse-ci.org
  version: v1alpha1
  names:
    kind: Pipeline
    plural: pipelines
    singular: pipeline