apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.concourse.concourse-ci.org
spec:
  scope: Namespaced
  group: concourse.concourse-ci.org # https://github.com/kubernetes-sigs/kubebuilder/issues/298
  version: v5alpha1
  names:
    kind: Pipeline
    plural: pipelines
    singular: pipeline